plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.rpg.aetherion"
    compileSdk = 35 //locl
    buildToolsVersion = "35.0.1" //lock

    defaultConfig {
        applicationId = "com.rpg.aetherion"
        minSdk = 21
        targetSdk = 35 //lock
        versionCode = 1
        versionName = "1.0"
        
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17 //lock
        targetCompatibility = JavaVersion.VERSION_17 //lock
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    
}
